module.exports = {
  ok: "success",
  userRegister: "Register successfull",
  unAuthorized: "You don't have permission to do this activity",
  options_compulsory: "Options are compulsory for multiple choice question",
  createAssignment: "Assignment created successfully",
  createAnnouncement: "Announcement created successfully",
  createQuestion: "Question created successfully",
  createMaterial: "Material created successfully",

  assignmentNotFound: "Assignments not found",
  announcementNotFound: "Announcement not found",

  materialNotFound: "Material not found",

  questionsNotFound: "Questions not found",
  questionFound: "Question found successfully",
  assignmentUpdated: "Assignment updated successfully",
  announcementUpdated: "Announcement updated successfully",

  materialUpdated: "Material updated successfully",

  assignmentFound: "Assignment found successfully",
  announcementFound: "Announcement found successfully",
  materialFound: "Material found successfully",

  questionsFound: "Questions found successfully",
  productAdded: "Product added successfully",
  giftAdded: "Gift added successfully",
  outOfStock: "Product is currently out of stock",
  orderCreated: "Order created successfully",
  NotFound: "Record Not Found ",
  emailAlreadyExist: "Email Already Exist",
  updateSuccess: "Updated successfully",
  deleteSuccess: "Deleted successfully",
  incorrectPassword: "Incorrect Email or Password",
  incorrectOldPassword: "Your password is incorrect",
  removeFromWishlist: "Campaign removed from wishlist",
  removeFromCart: "Campaign removed from cart",
  alreadyInCart: "Campaign is aready in cart",
  addToWishlist: "Campaign added to wishlist",
  passwordUpdate: "Password update successfull",
  emailSent: "Mail has been sent",
  serverError: "Internal Server Error",
  validationErrors: "Validation Errors",
  notVerified: "Your Email is Not Verified",
  teachersFound: "Teachers Found Successfully",
  recordAlreadyExist: "Record Already Exist",
  invitationSent: "Invitation Send Successfully",
  mailSent: "Mail Has Been Sent For Verification",
  sessionExpired: "Try Again! Session Expired",
  emailVerify: "Your Mail Has Been Verified Successfully",
  schoolExist: "School Already Exists",
  schoolRegistered: "School Registered Successfully",
  schoolUpdate: "School Updated Successfully",
  schoolDelete: "School Deleted Successfully",
  statsRecord: "All Stats Record",
  districtAlreadyExist: "District Already Exist",
  districtRegister: "District Register successfully",
  districtFound: "District Found successfully",
  districtNotFound: "District Not Found",
  districtUpdated: "District Updated successfully",
  districtDeleted: "District Deleted successfully",
  classAlreadyExist: "Class Already Exist",
  classRegister: "Class Register successfully",
  classNotFound: "Class Not Found",
  classFound: "Class Found Successfully",
  classUpdated: "Class Updated Successfully",
  classDeleted: "Class Deleted Successfully",
  pleaseInsert: "Please Insert",
  notEligible: "Sorry! You Are Not Eligible",
  districtUserNotFound: "District User Not Found",
  districtUsersFound: "District Users Found successfully",
  create: "Account Created Successfully",
  districtAllRecord: "District All Record",
  districtRecord: "District Statistics Record ",
  allClasses: "All Classes Found Successfully",
  studentsFound: "Students Found Successfully",
  limit: "limit exceeded",
  schoolNotFound: "School Not Found",
  schoolUsersFound: "School Users Found successfully",
  subjectsFound: "Subjects Found Successfully",
  schoolStats: "Found School Stats Successfully",
  schoolData: "Found School Data Successfully",
  teacherStats: "Teacher Stats Found Successfully",
  userNotExist: "User Not Exists",
  resetCode: "Reset Code Sent To Your Email",
  resetPassword: "password reset successfully",
  userExist: "User Already Exists",
  titleAlreadyExist: "Title Already Exist",
  lessonRegister: "Register successfull",
  questionUpdated: "Question Succesfully updated",
  answerSubmitted: "Answer submitted successfully",
};
